### ISSUE TITLE
Mismatched Pod and Info

### ISSUE THREAD

**Issue by yoiang** [CocoaPods/search.cocoapods.org#101]
I've only noticed the issue here: https://cocoapods.org/pods/MFStoryboardPushSegue

Notice the info provided does not match MFStoryboardPushSegue, instead it appears to be from QueryKit's pod

**Comment by floere** [comment]
@orta Am I remembering correctly that you did some work on this type of issue?

**Comment by orta** [comment]
Hrm, might need  a re-deploy.

**Comment by yoiang** [comment]
I'm unsure which Cocoapod project to add report this issue, slightly different and not sure if it relates to the above:
A number of pods pages haven't refreshed in a few versions, I've only noticed it so far with personal pods.
See https://cocoapods.org/pods/SegueingInfo and https://cocoapods.org/pods/AdorkableAPIBase

Thanks folks!

**Comment by floere** [comment]
@orta This may have been fixed with a related release in the last few days/weeks?

**Comment by floere** [comment]
I'm closing this as an equal issue exists on the cocoapods.org repo: https://github.com/CocoaPods/cocoapods.org/issues/162

**Comment by yoiang** [comment]
@floere should I post about the non-refreshed pod pages as a new issue or in https://github.com/CocoaPods/cocoapods.org/issues/162?

re: https://cocoapods.org/pods/SegueingInfo is two+ pod versions behind the README.

**Comment by floere** [comment]
@yoiang If you could add the info (if they are still non-refreshed) to the 162 issue, that would be great, thanks! :)

SegueingInfo is currently at 2.1.0, which is the latest version in the Specs repository (https://github.com/CocoaPods/Specs/tree/master/Specs/SegueingInfo). And AdorkableAPIBase is at 0.3.1. It's possible a fix has been implemented by @orta a short while back.
