### ISSUE TITLE
Show latest stable version instead of pre-release versions

### ISSUE THREAD

**Issue by f2prateek** [CocoaPods/search.cocoapods.org#102]
I have a [pod](https://cocoapods.org/pods/Segment-Mixpanel) with alpha releases ([`2.9.0-alpha`](https://github.com/CocoaPods/Specs/tree/master/Specs/Segment-Mixpanel/2.9.0-alpha)), and I've made a stable release ([`1.0.0`](https://github.com/CocoaPods/Specs/tree/master/Specs/Segment-Mixpanel/1.0.0)). The website [shows `2.9.0-alpha`](https://cloudup.com/c38cdmr7C_R) as the latest release, instead of `1.0.0`, which is what [CocoaDocs](http://cocoadocs.org/docsets/Segment-Mixpanel/) and the normal dependency resolution point to.

Ref: https://github.com/CocoaPods/Specs/pull/13644#issuecomment-158203106

cc @floere

**Comment by orta** [comment]
Offhand:

This is not quite as simple as adding a pre-release check in the resolver, there will need to be work done in CocoaDocs to only ship CocoaPods metrics for stable release builds. It's currently assuming that the latest release is what we'll be showing in CocoaPods.org - then we need to re-generate the README/CHANGELOGs for every pod.

We'd also need a place to indicate that there are pre-release builds available in the pod page, as using something like ReactiveCocoa for which the latest build won't work unless you're using an old Xcode.

**Comment by floere** [comment]
@f2prateek Thanks for entering it here! We're currently in deliberations whether search (and the website etc., what @orta is referring to) should be changed to prefer the latest stable version over the latest version.

**Comment by f2prateek** [comment]
Thanks. For my own reference in the future — what's the best way to do have pre-release versions with the CocoaPods infrastructure currently? I might have a library `1.1.2` and want to do a pre-release version for `1.2.0`? If I tag it as `1.2.0-alpha` (or beta or RC), it would show up as the latest version on the CocoaPods site which isn't ideal.

**Comment by floere** [comment]
@f2prateek That's the way to do it (to follow semver). Yes, it would show up as such – in the specific described case, I do understand less why it's not ideal. I do understand it better in the e.g. 7.0-beta + 1.0 case.

**Comment by floere** [comment]
@f2prateek In roughly 2 days the 1.0.0 result will be shown on cocoapods.org – see the blog post here: http://blog.cocoapods.org/Release-Versions-Only/

**Comment by floere** [comment]
* [ ] Flip the switch.

**Comment by f2prateek** [comment]
@floere Awesome :shipit:

**Comment by floere** [comment]
Switch: flipped :rocket:

**Comment by phatblat** [comment]
Completely agree with the direction here but have a question: now that only released versions are showing up in the search how does one search for prerelease versions?

My current use case, I'm trying to search for `Kal` which has only one prerelease version which shows up in the `pod search` output, but doesn't appear through the website search or in the API:
http://search.cocoapods.org/api/v1/pods.flat.hash.json?query=name:Kal

```
-> Kal (1.0rc1)
   A calendar component for the iPhone (the UI is designed to match MobileCal).
   pod 'Kal', '~> 1.0rc1'
   - Homepage: http://www.thepolypeptides.com
   - Source:   https://github.com/klazuka/Kal.git
   - Versions: 1.0rc1 [master repo]
```

**Comment by floere** [comment]
@phatblat We do not cover that case anymore. In the eyes of search, unreleased pods do not exist. Pod authors need to promote unreleased pods via other means.

**Comment by phatblat** [comment]
Gotcha. Then I guess this would actually be an issue with the CLI since it is showing up there.

**Comment by floere** [comment]
@phatblat Not necessarily – we can live with a little inconsistency in the two approaches.
