### ISSUE TITLE
Pod not showing up in search

### ISSUE THREAD

**Issue by orta** [CocoaPods/search.cocoapods.org#105]
From https://github.com/CocoaPods/CocoaPods/issues/6084

🌈

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.

Yes. i'm on v1.1.1

>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
`pod trunk push`

## What did you expect to happen?
The pod to show up on cocoapods.org, cocoapods search, and to be available via Podfiles.

## What happened instead?
The pod url now [works](https://cocoapods.org/pods/PayPalCommerce), and it now is available via Podfiles.
But, it's not showing up in [search](https://cocoapods.org/?q=paypalcommerce).

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/tolar/.rvm/rubies/ruby-2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 048c4b6626eb8e7488536aa1388afc038b5ac35c
```

### Installation Source

```
Executable Path: /Users/tolar/.rvm/rubies/ruby-2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

**Comment by orta** [comment]
Not showing on the API
http://search.cocoapods.org/api/v1/pods.flat.hash.json?query=paypal

Doesn't have any stats in trunk, but that should be fine
http://metrics.cocoapods.org/api/v1/pods/PayPalCommerce

**Comment by rhaining** [comment]
Thanks @orta!

**Comment by rhaining** [comment]
Some context: i initially pushed this on friday, when all the DNS problems were happening, so it could've just been some temporary glitch related to that?

**Comment by DanToml** [comment]
I've been looking into this, and it looks like it could be because there are no non-beta releases? https://github.com/CocoaPods/search.cocoapods.org/blob/master/lib/models/pod.rb#L86

**Comment by orta** [comment]
Yeah - it is, thanks @DanToml. We wrote up why in http://blog.cocoapods.org/Release-Versions-Only/

Alright, then this is closing as working as expected.

**Comment by rhaining** [comment]
thanks y'all! i appreciate your help!
