### ISSUE TITLE
Search isn't working

### ISSUE THREAD

**Issue by NinoScript** [CocoaPods/search.cocoapods.org#107]
Searching in cocoapods.org is currently broken, nothing happens.

Console outputs this:
`XMLHttpRequest cannot load https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=something&ids=20&offset=0&sort=quality. Origin https://cocoapods.org is not allowed by Access-Control-Allow-Origin.`

Seems to be this same issue: https://github.com/CocoaPods/cocoapods.org/issues/262

**Comment by floere** [comment]
Thanks for the issue! 😊 The problem was a 503 on the server – the full error message in the console noted this as well (`The response had HTTP status code 503.`). Cheers!
