### ISSUE TITLE
Search API not working

### ISSUE THREAD

**Issue by Kapeli** [CocoaPods/search.cocoapods.org#116]
The search API seems to not be working anymore (e.g. http://search.cocoapods.org/api/v1/pods.flat.hash.json?query=name:AFNetworking)

This URL seems to be working: http://aws-search.cocoapods.org/api/v1/pods.flat.hash.json?query=name:AFNetworking

Should I be using aws-search.cocoapods.org instead of search.cocoapods.org?

Could `search.cocoapods.org` be made to point to `aws-search.cocoapods.org`? The URL is hardcoded in Dash.

**Comment by orta** [comment]
We've been giving the AWS version a transition period, I think it makes sense to do change the DNS  back to point to that - opinions @DanToml ?

**Comment by DanToml** [comment]
@orta let's do it

**Comment by Kapeli** [comment]
Any ETA on this? If it's not a quick fix, please let me know so I can fix things from Dash's end.

**Comment by orta** [comment]
Good timing, just did it

**Comment by orta** [comment]
DNS should be re-directing both search and search-aws to our AWS instance now

**Comment by Kapeli** [comment]
Working again. Thank you! 👍

**Comment by mohammadkalim** [comment]
not working ... :(
