### ISSUE TITLE
Move pod where pod.name == query to top again.

### ISSUE THREAD

**Issue by floere** [CocoaPods/search.cocoapods.org#73]
* Change sorting
* Perhaps show in frontend that it has been moved?

**Comment by orta** [comment]
+1, would still love this.

**Comment by lazerwalker** [comment]
Yeah, +1. This has frustrated me in the past.

**Comment by floere** [comment]
+0, indifferent about it.

**Comment by floere** [comment]
Just kidding. I put it on my list for Tue.

**Comment by floere** [comment]
@orta Any ideas how to nicely show it's been moved in the frontend?

**Comment by orta** [comment]
Hrm, not ATM
