### ISSUE TITLE
Memory spikes when sending stats

### ISSUE THREAD

**Issue by floere** [CocoaPods/search.cocoapods.org#76]
Because we fork for sending the stats to status.cocoapods.org, the memory spikes.

Why? Are we writing when we do so, triggering a COW?

**Comment by floere** [comment]
Copy-On-Write, not a :cow: ;)

**Comment by alloy** [comment]
![](https://i.imgur.com/rp7zs.gif)

**Comment by alloy** [comment]
Can you reproduce it locally and do you have a debug build of Ruby? If so, it's probably easiest to do some heap analysis? (e.g. with Instruments.app's Heapshot instrument.)

**Comment by floere** [comment]
That's probably possible :) And I keep forgetting about Instrument.app.

This is not an actual problem we have (it's ok to go over the memory limit for a short time), just something I am wondering about.

**Comment by alloy** [comment]
Ah ok, well, there was your half-yearly reminder about Instruments.app ;)

**Comment by floere** [comment]
I've already forgotten about it again ;)

**Comment by alloy** [comment]
Sorry, won’t remind you for another 181.5 days!

**Comment by floere** [comment]
@alloy Let's see how Ruby 2.2 fares. Maybe it won't do a COW when just accessing a hash.

**Comment by floere** [comment]
@alloy MUST REMEMBAH

**Comment by orta** [comment]
lol. COW.

**Comment by AliSoftware** [comment]
![](http://i.giphy.com/Vp3ftHKvKpASA.gif)

**Comment by floere** [comment]
C'est réparé!
