### ISSUE TITLE
Wrong links in search results

### ISSUE THREAD

**Issue by yas375** [CocoaPods/search.cocoapods.org#78]
**Steps:**
1. Open cocoapods.org
2. Enter 'confirmation' as a search query.
3. You should see `MRConfirmationAlertView` in search results.
4. Click on its name or on the Site link.

Expected: it opens https://github.com/mricketson/MRConfirmationAlertView (according to [the spec](https://github.com/CocoaPods/Specs/blob/7c7e634f9f0a688444f9cf024db8ccd79d7a2a38/Specs/MRConfirmationAlertView/1.0.0/MRConfirmationAlertView.podspec.json#L6))
Result: it opens https://github.com/mattt/TransformerKit

![2015-01-20_1914](https://cloud.githubusercontent.com/assets/217368/5820859/fa1f2ce6-a0d8-11e4-80b5-626e9abea942.png)

P.S. I'm sorry if I choose wrong repository to open an issue in. Maybe it should be under cocoapods/cocoapods.org instead?

**Comment by floere** [comment]
No, it's fine as it's not clear if it's a search or cocoapods.org issue. I'm guessing it may be the JS in cp.org. @orta?

**Comment by orta** [comment]
Interesting, will need to look in the db for this. The site is pretty dumb, it takes whatever from the results.

**Comment by orta** [comment]
Yep, looks like, the first version of the spec included that as the homepage: https://github.com/mricketson/MRConfirmationAlertView/blob/master/MRConfirmationAlertView.podspec

Later versions fixed this, but we must be grabbing that pod_version ( presumably you're doing a `.first` somewhere  in search )

**Comment by floere** [comment]
Good job! :) I'll have to check how search gets the last version. It uses Gem::Version, but I could have implemented it wrong.

**Comment by floere** [comment]
The code appears to correctly use the right version. But I can't check for this pod. What is the latest version, what the one whose spec. Is used?

**Comment by segiddins** [comment]
@floere it should be using `Pod::Version` :)

**Comment by orta** [comment]
![screen shot 2015-01-20 at 12 13 48](https://cloud.githubusercontent.com/assets/49038/5821946/cf3b69e4-a09d-11e4-9ecf-1b067d3b1469.png)

`15618` has Mattt's link, it correlates to Podspec version 1.0.0

**Comment by floere** [comment]
Version 15618?

**Comment by floere** [comment]
@orta What is the name of version #15618?

**Comment by orta** [comment]
It's version  1.0.0

**Comment by orta** [comment]
all 5 commits are associated with the same `pod_version`.

**Comment by orta** [comment]
these are the reasons why we discourage allowing editing via PRs.

**Comment by kylef** [comment]
Btw: https://github.com/CocoaPods/Specs/commit/eac152fa1fdef4f305fc67cd2a6a89661f3ca16f

**Comment by floere** [comment]
That means we're not using the right commit.

@orta What do you mean by "these"?

**Comment by floere** [comment]
Ok, got it. Thanks! @yas375 You've helped me find a tiny bug related to this issue.

**Comment by orta** [comment]
well, ideally we should have a 1 to 1 ratio of `commit` to `version` otherwise we don't really know which is the most valid one. In theory we'd need to do a order by `created_by`.

**Comment by floere** [comment]
Fixed: http://cocoapods.org/?q=confirmation Cheers!

**Comment by yas375** [comment]
Just a little more than an hour... You guys rock!  :star2:

**Comment by orta** [comment]
( Also, @kylef that makes sense )

**Comment by floere** [comment]
@yas375 Thanks! I was on a bad phone connection, otherwise we may have done it in 20 minutes ;)

**Comment by floere** [comment]
Btw, the problem was that I had assumed generally a 1:1 correspondence, so a random commit was taken.

**Comment by yas375** [comment]
> @yas375 Thanks! I was on a bad phone connection, otherwise we may have done it in 20 minutes ;)

)))) :+1:
