### ISSUE TITLE
Implement stemming of words

### ISSUE THREAD

**Issue by kylef** [CocoaPods/search.cocoapods.org#79]
We should figure the root form of all the words when indexing and searching.

There are a few benefits of this:

- Marginally less memory will be needed to store the stemmed version of the word when indexing (every little *bit* helps)
- We will be able to get consistent results regardless of the pluralisation (and other factors) of search terms.
  - (`header` vs `headers`)
  - (`heading` vs `head`)
  - etc
- It gives @floere a fun task to do over the weekend.

**Comment by floere** [comment]
Nitpick: Not the root form, the stem, actually – hence stemming :)

**Comment by floere** [comment]
Sadly, as we do not search full text, we cannot easily use stemming. We can't just stem all search terms, as for example a snowball stemmer will think "ios" is "io" stemmed.

**Comment by floere** [comment]
See https://github.com/floere/picky/issues/138

**Comment by floere** [comment]
Done and released. Check the summary of PonyDebugger: http://cocoapods.org/?q=networking

**Comment by AliSoftware** [comment]
Awesome! :dancers:
