### ISSUE TITLE
"Link" is returned incorrectly to NSUIColor+FlatColors pod

### ISSUE THREAD

**Issue by kylef** [CocoaPods/search.cocoapods.org#81]
Not saying the issue is necessarily in the search API, but it seem it is. Looking at the [podspecs](https://github.com/CocoaPods/Specs/tree/master/Specs/NSUIColor%2BFlatColors) the link is correct. But the [search API](http://search.cocoapods.org/api/v1/pods.picky.hash.json?query=NSUIColor&ids=20&offset=0&sort=popularity) is returning `http://github.com/http://www.github.com/emiscience/NSUIColor-FlatColors` as the link to this pod's homepage. It seems to be prepending `http://github.com/` to the URI.

**Comment by floere** [comment]
It is. I'm looking at it on Tuesday if nobody is faster.

**Comment by floere** [comment]
This has been fixed. Cheers :)
