### ISSUE TITLE
Support searching for the dominant language in Pods

### ISSUE THREAD

**Issue by orta** [CocoaPods/search.cocoapods.org#82]
![screen shot 2015-03-09 at 09 27 48](https://cloud.githubusercontent.com/assets/49038/6555738/92172a8c-c63e-11e4-8886-a9436b25626f.png)

We should have data on all pods' language now. Would be nice to be able to say "only swift pods" by looking at the dominant language.

**Comment by floere** [comment]
Great!

**Comment by floere** [comment]
So we take `dominant_language || github.language`, using Github as a fallback.

**Comment by orta** [comment]
Yes!

**Comment by orta** [comment]
This is almost perfect. The recommended results are coming back as "Swift XX" - is there a way to remove the Swift prefix?

![screen shot 2015-04-25 at 9 19 49 am](https://cloud.githubusercontent.com/assets/49038/7333038/4e367e18-eb2c-11e4-814f-56ed6452b204.png)

https://cocoapods-org.herokuapp.com/?q=lang%3Aswift%20xc

**Comment by floere** [comment]
Yes there is, we needed to do the same thing with the platform.

**Comment by floere** [comment]
Done!
