### ISSUE TITLE
Add recency sorting options.

### ISSUE THREAD

**Issue by floere** [CocoaPods/search.cocoapods.org#85]
Sorted by release date?

**Comment by kylef** [comment]
That or also recent "commits" (last commit date) from metrics.

**Comment by floere** [comment]
After adding this last night I noticed it's a bit unsatisfactory not to put together some nice use cases.

What are the cases where somebody needs recency?

**Comment by floere** [comment]
Let's stick with popularity and quality as the main sort options then, with forks etc. as optionals.
