### ISSUE TITLE
Pods should be considered deprecated if there is just `deprecated_in_favor_of`

### ISSUE THREAD

**Issue by orta** [CocoaPods/search.cocoapods.org#91]
Right now it looks like a pod like [mailcore2](https://github.com/CocoaPods/Specs/blob/master/Specs/mailcore2/0.4.7/mailcore2.podspec.json) gets its deprecation ignored due to `deprecated` not being set to true, which makes sense, but isn't really a reflection on how people are actually using `deprecated_in_favor_of`.

**Comment by floere** [comment]
I added this, but now that I see it: https://cocoapods.org/?q=mailcore2 I don't think the search engine should decide this for frontends. Instead, should not trunk decide that if deprecated_in_favor_of is set, then deprecated is true.

I guess I am asking whether this is a general rule. If so, it should go into trunk.
