### ISSUE TITLE
Return information on indexing status

### ISSUE THREAD

**Issue by floere** [CocoaPods/search.cocoapods.org#96]
The search engine knows exactly how many pods have been indexed after a restart. Return the percentage of indexed pods to help the UI in determining a rough estimate of pods that would be found when fully indexed (and show the exact number if all are indexed).

* [x] Decide on an attribute name.
* [x] Add top-level attribute.
* [x] Return on the Picky format.
* [x] Update in all specs.

**Comment by floere** [comment]
* [ ] Decide on an attribute name.
* [ ] Add top-level attribute.
* [ ] Return in all formats.

**Comment by floere** [comment]
Attribute name: `indexed_ratio: [0.0-1.0]`

**Comment by segiddins** [comment]
`indexing_progress` ?

**Comment by floere** [comment]
Good idea!
