### ISSUE TITLE
Support tvOS and watchOS as platforms

### ISSUE THREAD

**Issue by orta** [CocoaPods/search.cocoapods.org#98]
![screen shot 2015-09-26 at 09 18 22](https://cloud.githubusercontent.com/assets/49038/10116568/8d5fcbfe-642f-11e5-8175-365675c6c9ed.png)

This baby is going to want to turn into 

![screen shot 2015-09-26 at 09 19 26](https://cloud.githubusercontent.com/assets/49038/10116574/b419e568-642f-11e5-9e3c-4b7bd486fdd7.png)

I'm thinking of removing "universal" as it ceases to make too much sense with 4 platforms. The tvOS support is merged in master for CocoaPods. Ideally being released next week.

**Comment by floere** [comment]
@orta Do you want to prepare cocoapods.org, and I will do search?

**Comment by orta** [comment]
Sure, I can build it whenever :+1:

**Comment by floere** [comment]
I can add it to search without impacting the current search frontend :)

**Comment by floere** [comment]
@orta But can you provide the strings that map to both watch and tv?

**Comment by orta** [comment]
CocoaPods would generate json like:

```
  "platforms": {
    "ios": "8.0",
    "osx": "10.9",
    "watchos": "2.0",
    "tvos": "9.0"
  },
```

So we can go with those :+1:

**Comment by floere** [comment]
Cheers!

**Comment by floere** [comment]
It's already built-in:

* `watchos`: http://search.cocoapods.org/api/v1/pods.picky.hash.json?query=platform:watchos&ids=10
* `tvos`: http://search.cocoapods.org/api/v1/pods.picky.hash.json?query=platform:tvos&ids=10 (none yet?)

**Comment by orta** [comment]
ah! perfect!

**Comment by floere** [comment]
I'll leave this open on this repo – feel free to "move" to the cp.org repo. Or not.

**Comment by orta** [comment]
Nah, you're good. I'll get one on cp.org
