### ISSUE TITLE
Getting "Internal Server Error" when trying to open a particular pod page

### ISSUE THREAD

**Issue by yas375** [CocoaPods/search.cocoapods.org#99]
I looked through different repos of CocoaPods organization and this one seems to be most relevant. I apologize if this is the wrong repo. Please let me know if I should resubmit this to some other repo.

Each time I access [page for SSZipArchive pod](https://cocoapods.org/pods/SSZipArchive) I'm getting "Internal Server Error".

<img width="506" alt="2015-09-27_1855" src="https://cloud.githubusercontent.com/assets/217368/10126555/52cafab6-6549-11e5-9dbf-e83d41226e97.png">

Other pod's pages work fine. 

I found the reference to this lib using search:

<img width="751" alt="2015-09-27_1858" src="https://cloud.githubusercontent.com/assets/217368/10126572/a9e5030a-6549-11e5-8f83-727920cf3a41.png">

**Comment by floere** [comment]
Hi Victor! The perfect repo would be https://github.com/CocoaPods/cocoapods.org/issues – mind moving it there? Thanks! :rocket:

**Comment by yas375** [comment]
Hi Florian! Thanks! :+1: 

https://github.com/CocoaPods/cocoapods.org/issues/214
